services:
  persistant_volume_db:
    image: postgres:16
    container_name: carmodpicker_persistant_volume_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db_network
  unit_test_db:
    image: postgres:16
    container_name: carmodpicker_unit_test_db
    env_file:
      - .env.test # Load environment variables from .env.test file
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db_network

  fastapi_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carmodpicker_backend
    env_file:
      - .env
    ports:
      - "8000:8000" # (uvicorn default)
    depends_on:
      persistant_volume_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s # Gives the app time to start up before first health check
    networks:
      - carmodpicker_network
      - db_network

volumes:
  postgres_data:

networks:
  carmodpicker_network:
    external: true # Declare that this network is created outside of this compose file
  db_network:
    driver: bridge
