"""add missing models

Revision ID: 2a9e63f7d158
Revises: 63c8a5eeb933
Create Date: 2025-05-01 19:26:10.199620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9e63f7d158'
down_revision: Union[str, None] = '63c8a5eeb933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_lists_description'), 'build_lists', ['description'], unique=False)
    op.create_index(op.f('ix_build_lists_id'), 'build_lists', ['id'], unique=False)
    op.create_index(op.f('ix_build_lists_name'), 'build_lists', ['name'], unique=False)
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('part_type', sa.String(), nullable=True),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('build_list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_list_id'], ['build_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parts_description'), 'parts', ['description'], unique=False)
    op.create_index(op.f('ix_parts_id'), 'parts', ['id'], unique=False)
    op.create_index(op.f('ix_parts_manufacturer'), 'parts', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_parts_name'), 'parts', ['name'], unique=False)
    op.create_index(op.f('ix_parts_part_number'), 'parts', ['part_number'], unique=False)
    op.create_index(op.f('ix_parts_part_type'), 'parts', ['part_type'], unique=False)
    op.create_index(op.f('ix_parts_price'), 'parts', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parts_price'), table_name='parts')
    op.drop_index(op.f('ix_parts_part_type'), table_name='parts')
    op.drop_index(op.f('ix_parts_part_number'), table_name='parts')
    op.drop_index(op.f('ix_parts_name'), table_name='parts')
    op.drop_index(op.f('ix_parts_manufacturer'), table_name='parts')
    op.drop_index(op.f('ix_parts_id'), table_name='parts')
    op.drop_index(op.f('ix_parts_description'), table_name='parts')
    op.drop_table('parts')
    op.drop_index(op.f('ix_build_lists_name'), table_name='build_lists')
    op.drop_index(op.f('ix_build_lists_id'), table_name='build_lists')
    op.drop_index(op.f('ix_build_lists_description'), table_name='build_lists')
    op.drop_table('build_lists')
    # ### end Alembic commands ###
