"""add car vins

Revision ID: 8640238ee897
Revises: 2a9e63f7d158
Create Date: 2025-05-10 19:19:27.166814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8640238ee897'
down_revision: Union[str, None] = '2a9e63f7d158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('vin', sa.String(), nullable=True))
    op.create_index(op.f('ix_cars_vin'), 'cars', ['vin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cars_vin'), table_name='cars')
    op.drop_column('cars', 'vin')
    # ### end Alembic commands ###
