"""remove buildlist and part

Revision ID: 9fad665febcc
Revises: 73edcebab774
Create Date: 2025-04-28 20:39:21.300628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fad665febcc'
down_revision: Union[str, None] = '73edcebab774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_buildlists_id', table_name='buildlists')
    op.drop_index('ix_buildlists_name', table_name='buildlists')
    op.drop_index('ix_buildlists_owner_id', table_name='buildlists')
    op.drop_table('buildlists')
    op.drop_index('ix_parts_buildlist_id', table_name='parts')
    op.drop_index('ix_parts_description', table_name='parts')
    op.drop_index('ix_parts_id', table_name='parts')
    op.drop_index('ix_parts_name', table_name='parts')
    op.drop_table('parts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('buildlist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='parts_pkey')
    )
    op.create_index('ix_parts_name', 'parts', ['name'], unique=False)
    op.create_index('ix_parts_id', 'parts', ['id'], unique=False)
    op.create_index('ix_parts_description', 'parts', ['description'], unique=False)
    op.create_index('ix_parts_buildlist_id', 'parts', ['buildlist_id'], unique=False)
    op.create_table('buildlists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='buildlists_pkey')
    )
    op.create_index('ix_buildlists_owner_id', 'buildlists', ['owner_id'], unique=False)
    op.create_index('ix_buildlists_name', 'buildlists', ['name'], unique=False)
    op.create_index('ix_buildlists_id', 'buildlists', ['id'], unique=False)
    # ### end Alembic commands ###
