"""Build out car build_list and part tables

Revision ID: c1c2b204718f
Revises: f61439fd5af3
Create Date: 2025-04-30 22:43:06.010911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c2b204718f'
down_revision: Union[str, None] = 'f61439fd5af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('trim', sa.String(), nullable=True))
    op.add_column('cars', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('cars', 'make',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cars', 'model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cars', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_cars_trim'), 'cars', ['trim'], unique=False)
    op.create_foreign_key(None, 'cars', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_index(op.f('ix_cars_trim'), table_name='cars')
    op.alter_column('cars', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cars', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cars', 'make',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('cars', 'user_id')
    op.drop_column('cars', 'trim')
    # ### end Alembic commands ###
