"""add_images_to_all_models

Revision ID: dfae6a9a4202
Revises: 51a460dc3716
Create Date: 2025-06-11 21:51:52.661452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfae6a9a4202'
down_revision: Union[str, None] = '51a460dc3716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_lists', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('cars', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('parts', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_url')
    op.drop_column('parts', 'image_url')
    op.drop_column('cars', 'image_url')
    op.drop_column('build_lists', 'image_url')
    # ### end Alembic commands ###
