"""add email verification column to users

Revision ID: e7568d04aab3
Revises: 497e9c24bfe8
Create Date: 2025-05-27 21:47:21.828055

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7568d04aab3"
down_revision: Union[str, None] = "497e9c24bfe8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email_verified", sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET email_verified = FALSE WHERE email_verified IS NULL")
    op.alter_column("users", "email_verified", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_verified")
    # ### end Alembic commands ###
