apiVersion: apps/v1
kind: Deployment
metadata:
  name: carmodpicker-backend
  labels:
    app: carmodpicker-backend
spec:
  replicas: 2 # Adjust as needed
  selector:
    matchLabels:
      app: carmodpicker-backend
  template:
    metadata:
      labels:
        app: carmodpicker-backend
    spec:
      imagePullSecrets:
        - name: regcred 
      initContainers:
      - name: wait-for-db
        image: postgres:16
        command: ['sh', '-c', 
          'until pg_isready -h postgres-svc -p 5432 -U $POSTGRES_USER; do echo waiting for database; sleep 2; done; echo database is ready']
        envFrom:
        - secretRef:
            name: postgres-secrets
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      - name: db-migrate
        image: webbpulse/carmodpicker:backend-latest
        imagePullPolicy: Always
        command: ["alembic", "upgrade", "head"]
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      containers:
      - name: fastapi-backend
        image: webbpulse/carmodpicker:backend-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets
        resources:
          requests:
            memory: "128Mi" # Adjust as needed
            cpu: "250m"    # Adjust as needed (0.25 CPU core)
          limits:
            memory: "256Mi" # Adjust as needed
            cpu: "500m"    # Adjust as needed (0.5 CPU core)
        livenessProbe:
          httpGet:
            path: / 
            port: 8000
          initialDelaySeconds: 30 
          periodSeconds: 30     # How often to probe
          timeoutSeconds: 10      
          failureThreshold: 3   
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30 # How often to probe
          timeoutSeconds: 10
          failureThreshold: 3