apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-job
  labels:
    app: db-migration
spec:
  ttlSecondsAfterFinished: 600  # Clean up after 10 minutes
  template:
    metadata:
      labels:
        app: db-migration
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      initContainers:
      - name: wait-for-db
        image: postgres:16
        command: ['sh', '-c', 
          'until pg_isready -h postgres-svc -p 5432 -U $POSTGRES_USER; do echo waiting for database; sleep 2; done; echo database is ready']
        envFrom:
        - secretRef:
            name: postgres-secrets
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      containers:
      - name: migration
        image: webbpulse/carmodpicker:backend-latest
        imagePullPolicy: Always
        command: ["alembic", "upgrade", "head"]
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
# CronJob for automated migrations (optional)
apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-migration-cronjob
spec:
  schedule: "0 2 * * *"  # Run at 2 AM daily
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600  # Clean up after 10 minutes
      template:
        metadata:
          labels:
            app: db-migration
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: regcred
          initContainers:
          - name: wait-for-db
            image: postgres:16
            command: ['sh', '-c', 
              'until pg_isready -h postgres-svc -p 5432 -U $POSTGRES_USER; do echo waiting for database; sleep 2; done; echo database is ready']
            envFrom:
            - secretRef:
                name: postgres-secrets
            resources:
              requests:
                memory: "32Mi"
                cpu: "50m"
              limits:
                memory: "64Mi"
                cpu: "100m"
          containers:
          - name: migration
            image: webbpulse/carmodpicker:backend-latest
            imagePullPolicy: Always
            command: ["alembic", "upgrade", "head"]
            envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
            resources:
              requests:
                memory: "64Mi"
                cpu: "100m"
              limits:
                memory: "128Mi"
                cpu: "200m" 